name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      -name: Checkout
       uses: actions/checkout@v2

      -name: Install dependencies
       run: npm ci

      -name: Build the app
       run: npm run build

      -name: Start the app
       run: npm start &

      -name: Run Cypress tests ğŸ§ª
       run: npm run cy:run

      